[project]
name = "pandas-analyst"
version = "0.1.0"
description = "MCP Server for local data analysis using Pandas."
authors = [
    {name = "ssghost", email = "ssprof0@gmail.com"},
]
requires-python = ">=3.10"
dependencies = [
    "duckdb>=0.9.0", 
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"